fileVersion: 1
id: 454734e0-0c8a-48c3-a006-6bb175bdc43b
name: CONFIG_ATP
operation:
  database: ""
  dataset: ""
  deployEnabled: true
  description: ""
  locationName: E_SC_SP
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 3cfbb4a3-98de-4268-9ac9-87b9d24e05ce
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(50)
        defaultValue: ""
        description: ""
        name: APPLICATION
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 1069aed6-13b3-4849-9f9e-9e8ed4dbeb35
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: MEASURE_TYPE
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 54772bd6-cf92-49ac-a878-68abf9632246
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: SOURCE
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: ab835b6d-1cf2-4536-9657-eaa738363ad2
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(10)
        defaultValue: ""
        description: ""
        name: FIELD_KEY
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: dd86ff89-788b-48ef-b229-6094069b6ceb
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: DEMAND_SUPPLY_TYPE_L0
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 5f28e7c2-4986-4386-aa1c-0c1344c6e403
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(10)
        defaultValue: ""
        description: ""
        name: ATP_CATEGORY
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 9dd2b1fe-9b83-4b1f-b65b-757eae81ba04
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(100)
        defaultValue: ""
        description: ""
        name: DEMAND_SUPPLY_TYPE_L1
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 48e6a887-57ba-4301-b0e7-f2c96cfc1e4e
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: EXPLODESW
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: ae990dfa-6e2c-481c-be4b-eb110e51db07
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: PARENTORDERTYPE
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b3580063-e58c-4f70-99a7-f26d48b99613
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(5)
        defaultValue: ""
        description: ""
        name: NPI_FLAG
        nullable: true
        primaryKey: false
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 0db84561-aba0-48ca-8400-6c542bfc575b
          stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
        config: {}
        dataType: VARCHAR(1)
        defaultValue: ""
        description: ""
        name: DELETION_FLAG
        nullable: true
        primaryKey: false
        uniqueKey: false
    join:
      joinCondition: FROM {{ ref('E_SC_SP', 'CONFIG_ATP') }}
  name: CONFIG_ATP
  schema: ""
  sqlType: Source
  table: CONFIG_ATP
  type: sourceInput
  version: 1
type: Node
