fileVersion: 1
id: 8cbf5bc7-3435-4166-ad10-36fea37df437
name: END_ITEM_DMD_TYPE_CONFIG_ATP
operation:
  config:
    insertStrategy: INSERT
    postSQL: ""
    preSQL: ""
    testsEnabled: true
    truncateBefore: true
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: E_SC_TEMP
  materializationType: view
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 76c4de15-7a27-4bd0-b05b-dd4afde9cdbe
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(50)
        description: ""
        name: APPLICATION
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3cfbb4a3-98de-4268-9ac9-87b9d24e05ce
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d13ac501-0252-4051-a7c2-7f3bc21b271f
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(100)
        description: ""
        name: MEASURE_TYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1069aed6-13b3-4849-9f9e-9e8ed4dbeb35
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 016e1721-2677-4950-9393-55cff1a17209
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(100)
        description: ""
        name: SOURCE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 54772bd6-cf92-49ac-a878-68abf9632246
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: da1054a2-e0d1-44ec-8bf4-ed42df21deea
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(10)
        description: ""
        name: FIELD_KEY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ab835b6d-1cf2-4536-9657-eaa738363ad2
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 0218b216-2623-4d40-ad20-e0a0bdc6e4b9
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(100)
        description: ""
        name: DEMAND_SUPPLY_TYPE_L0
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: dd86ff89-788b-48ef-b229-6094069b6ceb
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 22157a6c-ac28-480f-9479-427e56196207
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(10)
        description: ""
        name: ATP_CATEGORY
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5f28e7c2-4986-4386-aa1c-0c1344c6e403
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 04fa5727-a445-4ba4-990c-e21d206332f1
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(100)
        description: ""
        name: DEMAND_SUPPLY_TYPE_L1
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 9dd2b1fe-9b83-4b1f-b65b-757eae81ba04
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 7b7e5f94-78d8-4d3b-9374-a06983d87c52
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(5)
        description: ""
        name: EXPLODESW
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 48e6a887-57ba-4301-b0e7-f2c96cfc1e4e
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: a9902d1a-c360-4653-a969-6e8d49aab99a
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(5)
        description: ""
        name: PARENTORDERTYPE
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ae990dfa-6e2c-481c-be4b-eb110e51db07
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c9e3a84a-b59e-49eb-9654-5309bce6e68b
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(5)
        description: ""
        name: NPI_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: b3580063-e58c-4f70-99a7-f26d48b99613
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 33429bb2-047c-4015-865b-652aa9470aa5
          stepCounter: 8cbf5bc7-3435-4166-ad10-36fea37df437
        config: {}
        dataType: VARCHAR(1)
        description: ""
        name: DELETION_FLAG
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0db84561-aba0-48ca-8400-6c542bfc575b
                stepCounter: 454734e0-0c8a-48c3-a006-6bb175bdc43b
            transform: ""
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          CONFIG_ATP: 95b01679-affc-41be-bff6-db00c3d598dc
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: E_SC_SP
            nodeName: CONFIG_ATP
        join:
          joinCondition: |-
            FROM {{ ref('E_SC_SP', 'CONFIG_ATP') }} "CONFIG_ATP"
            WHERE "CONFIG_ATP"."APPLICATION"='SUPPLY_PLAN_ANALYTICS' AND "CONFIG_ATP"."DELETION_FLAG"!='Y' AND "CONFIG_ATP"."MEASURE_TYPE"='TOTAL PRODUCTION GOAL' AND "CONFIG_ATP"."SOURCE"='SCHEDRCPTS'
        name: END_ITEM_DMD_TYPE_CONFIG_ATP
        noLinkRefs: []
  name: END_ITEM_DMD_TYPE_CONFIG_ATP
  overrideSQL: false
  schema: ""
  sqlType: Stage
  type: sql
  version: 1
type: Node
